# Generated by Django 4.2.6 on 2023-10-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('exp', models.CharField(blank=True, max_length=30, null=True)),
                ('grouping', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
