# Generated by Django 4.2.6 on 2023-10-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='img',
        ),
    ]
